/**
 * @aravi1008/ui — SVG Icon Sprite Builder
 * Reads all SVG files from icons/svg/ and combines them into dist/icons/sprite.svg
 * Also generates src/icons/_icon-list.scss with all icon classes
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'fs';
import { resolve, basename, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const ICONS_SRC = resolve(ROOT, 'icons/svg');
const ICONS_DIST = resolve(ROOT, 'dist/icons');

// Ensure output dir exists
if (!existsSync(ICONS_DIST)) {
  mkdirSync(ICONS_DIST, { recursive: true });
}

// Check if source icons exist
if (!existsSync(ICONS_SRC)) {
  mkdirSync(ICONS_SRC, { recursive: true });
  process.stdout.write('⚠️  icons/svg/ directory created but is empty. Add SVG files to build sprite.\n');
  process.exit(0);
}

const svgFiles = readdirSync(ICONS_SRC).filter((f) => f.endsWith('.svg'));

if (svgFiles.length === 0) {
  process.stdout.write('⚠️  No SVG files found in icons/svg/. Skipping sprite build.\n');
  process.exit(0);
}

// Build sprite
const symbols = svgFiles.map((file) => {
  const name = basename(file, '.svg');
  let content = readFileSync(resolve(ICONS_SRC, file), 'utf8');

  // Extract viewBox
  const viewBoxMatch = content.match(/viewBox="([^"]+)"/);
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24';

  // Strip outer <svg> tags, keep inner content
  content = content
    .replace(/<\?xml[^>]*\?>/gi, '')
    .replace(/<!DOCTYPE[^>]*>/gi, '')
    .replace(/<svg[^>]*>/gi, '')
    .replace(/<\/svg>/gi, '')
    .replace(/\s+/g, ' ')
    .trim();

  return `  <symbol id="${name}" viewBox="${viewBox}">\n    ${content}\n  </symbol>`;
});

const sprite = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display:none">
${symbols.join('\n')}
</svg>`;

writeFileSync(resolve(ICONS_DIST, 'sprite.svg'), sprite, 'utf8');

// Copy individual SVGs to dist/icons/
svgFiles.forEach((file) => {
  const content = readFileSync(resolve(ICONS_SRC, file), 'utf8');
  writeFileSync(resolve(ICONS_DIST, file), content, 'utf8');
});

// Generate SCSS icon list
const iconNames = svgFiles.map((f) => basename(f, '.svg'));
const scssContent = `// @aravi1008/ui — Generated icon list (${iconNames.length} icons)
// Auto-generated by scripts/build-icons.js — do not edit manually
// Source: icons/svg/*.svg

$av-icon-names: (
${iconNames.map((n) => `  '${n}'`).join(',\n')}
);

// Usage: <svg class="av-icon av-icon-md"><use href="/dist/icons/sprite.svg#icon-name"></use></svg>
`;

writeFileSync(resolve(ROOT, 'src/icons/_icon-list.scss'), scssContent, 'utf8');

process.stdout.write(`✅ Icon sprite built: ${iconNames.length} icons → dist/icons/sprite.svg\n`);
process.stdout.write(`✅ Icon list generated: src/icons/_icon-list.scss\n`);
